log_level = "debug"
[mysql]
host="127.0.0.1"
port=3306
database="yashan"
username="root"
password="123456"
#tables=["test_key_word"]
schemas=["yashan"]
exclude_tables=["data"]
#parallel=1
#parallel_per_table=1
#batch_size=1000
#query="where create_date < '2022-01-11 00:00:00'"
sample_lines=1000
#rows_only=true
#no_check_null_string=true

[yashandb]
host="127.0.0.1"
port=1688
username="sys"
password="yasdb_123"
remap_schemas=["SYS"]
case_sensitive = false # 是否大小写敏感，默认不敏感（全大写）